apiVersion: v1
kind: Service
metadata:
  name: fe-nginx-service
  #namespace: simple
spec:
  selector:
    app: fe-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  #type: LoadBalancer
  type: ClusterIP
