# Use an official Node.js runtime as the base image
FROM python:3.12.3-slim AS build

# h5py requires pkg-config
RUN apt-get update && \
    apt-get install -y \
    pkg-config \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory in the container to /app
WORKDIR /python

# Copy package.json and package-lock.json into the working directory
COPY ./backend/worker/requirements.txt ./
COPY ./parameters.npz ./

# Install the app dependencies inside the docker image
RUN pip install --no-cache-dir -r requirements.txt


# Define the command to run your app using CMD which defines your runtime
COPY ./backend/worker .

EXPOSE 3002

CMD ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "3002"]
