apiVersion: v1
kind: Service
metadata:
  name: be-py-service
  #namespace: simple
spec:
  selector:
    app: be-py
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  #type: LoadBalancer
  type: ClusterIP
