---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  # Argocd remove k8s app first and argocd state
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
project: default
source:
  repoURL: https://github.com/jnuho/cvn-yaml.git
  targetRevision: HEAD
  path: my-app
destination:
  server: https://kubernetes.default.svc
# SYNC POLICY
# Without manually use ArgoCd UI to 'sync' which deploys the changes
syncPolicy:
  automated:
    prune: true
    selfHeal: true
    allowEmpty: false
  syncOptions:
    - Validate=true
    - CreateNamespace=false
    - PrunePropagationPolicy=foreground
    - PruneLast=true
