apiVersion: v1
kind: Service
metadata:
  name: fe-nginx-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: fe-nginx
  ports:
    - protocol: TCP
      port: 8080
      # targetPort: 80
      targetPort: web
  # type: LoadBalancer
  type: ClusterIP
