apiVersion: v1
kind: Service
metadata:
  name: be-go-service
  namespace: simple
spec:
  selector:
    app: be-go
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer
