---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: default
  # NOTE!
  # associate the IAM role with k8s serviceaccount via OIDC provider!
  # put the printed output from `9-iam-test.tf`
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/test-oidc
---
# k get pods
# k exec aws-cli -- aws s3api list-buckets
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: aws-test
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["/bin/bash", "-c", "--"]
      args: [ "while true; do sleep 5; done"]
    tolerations:
      - operator: "Exists"
        effect: "NoSchedule"