name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      # fe-nginx
      - 'web/**'
      # be-go
      - 'go.mod'
      - 'go.sum'
      - 'backend/web/**'
      - 'cmd/backend-web-server/**'
      # be-py
      - 'backend/worker/**'
      # dockerfiles
      - 'dockerfiles/**'

jobs:
  build-go:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for Go
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./dockerfiles/Dockerfile-go
        push: true
        tags: jnuho/be-go:latest
        cache-from: type=registry,ref=jnuho/be-go:latest
        cache-to: type=inline

  build-nginx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for Nginx
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./dockerfiles/Dockerfile-nginx
        push: true
        tags: jnuho/fe-nginx:latest
        cache-from: type=registry,ref=jnuho/fe-nginx:latest
        cache-to: type=inline

  build-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for Python
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./dockerfiles/Dockerfile-py
        push: true
        tags: jnuho/be-py:latest
        cache-from: type=registry,ref=jnuho/be-py:latest
        cache-to: type=inline
