name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      # fe-nginx
      - 'web/**'
      # be-go
      - 'go.mod'
      - 'go.sum'
      - 'backend/web/**'
      - 'cmd/backend-web-server/**'
      # be-py
      - 'backend/worker/**'

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  build-go:
    needs: docker-login
    runs-on: ubuntu-latest
    # if: |
    #   contains(github.event.head_commit.message, 'go.mod') ||
    #   contains(github.event.head_commit.message, 'go.sum') ||
    #   contains(github.event.head_commit.message, 'backend/web/') ||
    #   contains(github.event.head_commit.message, 'cmd/backend-web-server/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push Docker image for Go
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./dockerfiles/Dockerfile-go
        push: true
        tags: jnuho/be-go:latest
        cache-from: type=registry,ref=jnuho/be-go:latest
        cache-to: type=inline

  build-nginx:
    needs: docker-login
    runs-on: ubuntu-latest
    # if: contains(github.event.head_commit.message, 'web/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push Docker image for Nginx
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./dockerfiles/Dockerfile-nginx
        push: true
        tags: jnuho/fe-nginx:latest
        cache-from: type=registry,ref=jnuho/fe-nginx:latest
        cache-to: type=inline

  build-py:
    needs: docker-login
    runs-on: ubuntu-latest
    # if: contains(github.event.head_commit.message, 'backend/worker/')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push Docker image for Python
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./dockerfiles/Dockerfile-py
        push: true
        tags: jnuho/be-py:latest
        cache-from: type=registry,ref=jnuho/be-py:latest
        cache-to: type=inline