name: Build, Push Docker Images and update image tags in Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - 'go.mod'
      - 'go.sum'
      - 'backend/web/**'
      - 'cmd/backend-web-server/**'
      - 'pkg/weatherapi.go'
      - 'backend/worker/**'
      - 'dockerfiles/**'
    # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        service: [nginx, go, py]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./dockerfiles/Dockerfile-${{ matrix.service }}
        push: true
        tags: jnuho/${{ matrix.service }}:latest
        platforms: linux/amd64,linux/arm64
        cache-from: type=registry,ref=jnuho/${{ matrix.service }}:latest
        cache-to: type=inline

    - name: Create .env file (for Go service)
      if: matrix.service == 'go'
      run: |
        echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY}}" >> .env
        echo "PYTHON_URL=${{ secrets.PYTHON_URL}}" >> .env
        cat .env
